import turtle
from turtle import *
turtle=Turtle()
screen=Screen()
screen.setup(500,500)
turtle.speed(0)
turtle.penup()
turtle.pendown()
def wall(length,fill_color):
    turtle.fillcolor(fill_color)
    turtle.begin_fill()
    for i in range(4):
        turtle.forward(length)
        turtle.right(90)
    turtle.end_fill()
def roof(length,fill_color):
    turtle.fillcolor(fill_color)
    turtle.begin_fill()
    turtle.left(60)
    for i in range(3):
        turtle.forward(length)
        turtle.right(120)
    turtle.end_fill()
def door(lengthtop,lengthside,fill_color):
    turtle.setheading(90)
    turtle.fillcolor(fill_color)
    turtle.begin_fill()
    for i in range(2):
        turtle.forward(lengthside)
        turtle.right(90)
        turtle.forward(lengthtop)
        turtle.right(90)
    turtle.end_fill()
def window(length,fill_color,x,y):
    turtle.setheading(90)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    x_temp=x+length/2
    y_temp=y+length/2
    turtle.fillcolor(fill_color)
    turtle.begin_fill()
    for i in range(4):
        turtle.forward(length)
        turtle.right(90)
    turtle.end_fill()
    turtle.goto(x_temp,y)
    turtle.setheading(90)
    turtle.forward(length)
    turtle.penup()
    turtle.goto(x,y_temp)
    turtle.pendown()
    turtle.setheading(0)
    turtle.forward(length)
def star(length,x,y):
    turtle.setheading(90)
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.pencolor("yellow")
    turtle.pensize(3)
    middle=y+length/2
    for i in range(7):
        turtle.forward(length/2)
        turtle.right(45)
        turtle.goto(x,middle)
        turtle.back(length/2)
turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
wall(200,"lightgray")
turtle.penup()
turtle.goto(-100,0)
turtle.pendown()
roof(200,"pink")
turtle.penup()
turtle.goto(-25,-200)
turtle.pendown()
door(50,100,"brown")
window(50,"Blue",-88,-70)
window(50,"Blue",40,-70)
window(50,"Blue",-24,-70)
window(50,"Blue",-88,-160)
window(50,"Blue",40,-160)
star(30,200,200)
star(30,-153,200)
star(30,-123,176)
done()